# change to list chars of your dataset or use default vietnamese chars
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~° '
device: cuda
backbone: vgg19_bn
weights: https://vocr.vn/data/vietocr/vgg_transformer.pth
pretrain: https://vocr.vn/data/vietocr/vgg_transformer.pth
cnn:
  pretrained: True
  # pooling stride size
  ss:
    - [2, 2]
    - [2, 2]
    - [2, 1]
    - [2, 1]
    - [1, 1]
  # pooling kernel size
  ks:
    - [2, 2]
    - [2, 2]
    - [2, 1]
    - [2, 1]
    - [1, 1]
  # dim of ouput feature map
  hidden: 256
seq_modeling: transformer

transformer:
  d_model: 256
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  max_seq_length: 1024
  pos_dropout: 0.1
  trans_dropout: 0.1

optimizer:
  max_lr: 0.0003
  pct_start: 0.1

trainer:
  batch_size: 32
  print_every: 200
  valid_every: 4000
  iters: 72000
  # where to save our model for prediction
  export: ./weights/v3_transformerocr.pth
  checkpoint: ./checkpoint/trained_transformerocr_checkpoint.pth
  log: ./train.log
  # null to disable compuate accuracy, or change to number of sample to enable validiation while training
  metrics: null

dataset:
  # name of your dataset
  name: data
  # path to annotation and image
  data_root: "/kaggle/input/text-recognition-dataset/dataset"
  train_annotation: train_annotations.txt
  valid_annotation: test_annotations.txt
  # resize image to 32 height, larger height will increase accuracy
  image_height: 64
  image_min_width: 32
  image_max_width: 512

dataloader:
  num_workers: 2
  pin_memory: True

aug:
  image_aug: True
  masked_language_model: True

predictor:
  # disable or enable beamsearch while prediction, use beamsearch will be slower
  beamsearch: False

quiet: False
